name: flutter_mvvm_architecture
description: An opinionated MVVM architecture for Flutter.
version: 1.0.0
homepage:

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  mobx: ^2.4.0
  flutter_mobx: ^2.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:

